version: "4.31.1"
services:
  catologdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/mssql/server
  orderdb: 
    image: mcr.microsoft.com/mssql/server
  rabbitmq:
    image: rabbitmq:3.13.6-management

volumes:
  catologdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume:
